# Generated by Django 3.2.19 on 2023-09-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20230922_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.IntegerField(blank=True, default='91142', null=True),
        ),
    ]
